export const SET_NUTRITION = 'NUTRITION/SET_NUTRITION';
export const SET_SELECTED = 'NUTRITION/SET_SELECTED';
export const CLEAR_SELECTED = 'NUTRITION/CLEAR_SELECTED';
export const SORT_NUTRITION = 'NUTRITION/SORT_NUTRITION';
